### ISSUE TITLE
Horizontal overflow on the main page

### ISSUE THREAD

**Issue by d11r** [mrathi12/mrathi12.github.io#31]
Hey, I came across your FB intern blog post and jumped to your homepage. It had a bit of horizontal overflow.

I inspected it and just adding `overflow-x: hidden` to the `body` tag fixes the issue.

I'm really enjoying the content, though. Great job! Keep it up.

**Comment by mukul-rathi** [comment]
@strudra Thank you for the kind words and the fix!
